// Copyright (c) 2026, SvenGDK
// Licensed under the BSD 2-Clause License. See LICENSE file for details.

using CommunityToolkit.Mvvm.ComponentModel;
using System.Collections.Generic;
using System.Globalization;

namespace UFS2Tool.GUI.Services;

public partial class LocalizationManager : ObservableObject
{
    private static LocalizationManager? _instance;
    public static LocalizationManager Instance => _instance ??= new LocalizationManager();

    private Dictionary<string, string> _strings = null!;

    [ObservableProperty]
    private string _currentLanguage = "English";

    public LocalizationManager()
    {
        _strings = GetEnglishStrings();
    }

    public string this[string key] => _strings.TryGetValue(key, out var value) ? value : key;

    public void SetLanguage(string language)
    {
        CurrentLanguage = language;
        _strings = language switch
        {
            "Français" => GetFrenchStrings(),
            "Español" => GetSpanishStrings(),
            "Deutsch" => GetGermanStrings(),
            "中文" => GetChineseStrings(),
            "日本語" => GetJapaneseStrings(),
            "العربية" => GetArabicStrings(),
            "Русский" => GetRussianStrings(),
            "हिन्दी" => GetHindiStrings(),
            "한국어" => GetKoreanStrings(),
            "Türkçe" => GetTurkishStrings(),
            "Italiano" => GetItalianStrings(),
            "Português" => GetPortugueseStrings(),
            _ => GetEnglishStrings(),
        };
        OnPropertyChanged("Item");
    }

    public static readonly string[] AvailableLanguages =
    {
        "English",
        "Français",
        "Español",
        "Deutsch",
        "中文",
        "日本語",
        "العربية",
        "Русский",
        "हिन्दी",
        "한국어",
        "Türkçe",
        "Italiano",
        "Português",
    };

    private static Dictionary<string, string> GetEnglishStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Create, inspect, and manage UFS1/UFS2 filesystem images",
        ["OutputLog"] = "Output Log",
        ["Clear"] = "Clear",
        ["Detach"] = "Detach",

        // Tab Headers
        ["TabCreateFilesystem"] = "Create Filesystem",
        ["TabFilesystemOperations"] = "Filesystem Operations",
        ["TabMaintenance"] = "Maintenance",
        ["TabDeviceMount"] = "Device & Mount",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Settings",

        // Create Filesystem
        ["ImageFile"] = "Image File",
        ["ImagePathWatermark"] = "Path to output .img file",
        ["ImagePathHint"] = "Or populate via Input Directory below to create from existing files.",
        ["FilesystemOptions"] = "Filesystem Options",
        ["FilesystemFormat"] = "Filesystem Format",
        ["BlockSize"] = "Block Size",
        ["FragmentSize"] = "Fragment Size",
        ["SectorSize"] = "Sector Size",
        ["VolumeName"] = "Volume Name",
        ["VolumeNameWatermark"] = "Optional volume label",
        ["MinFreePercent"] = "Min Free %",
        ["Optimization"] = "Optimization",
        ["BytesPerInode"] = "Bytes per Inode",
        ["BytesPerInodeWatermark"] = "0 = auto",
        ["ImageSizeMB"] = "Image Size (MB)",
        ["InputDirectory"] = "Input Directory (makefs)",
        ["InputDirectoryWatermark"] = "Path to directory whose contents populate the image",
        ["InputDirectoryHint"] = "If set, image size is determined automatically from directory contents.",
        ["Flags"] = "Flags",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Erase Contents",
        ["DryRun"] = "Dry Run",
        ["CreateFilesystem"] = "Create Filesystem",

        // Filesystem Operations
        ["ImagePath"] = "Image Path",
        ["ImagePathFSWatermark"] = "Path to .img file",
        ["FSPath"] = "FS Path",
        ["Info"] = "Info",
        ["ListLS"] = "List (LS)",
        ["Extract"] = "Extract",
        ["Add"] = "Add",
        ["Delete"] = "Delete",
        ["Replace"] = "Replace",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Local Path",
        ["LocalPathWatermark"] = "Local file/directory for Add or Replace",
        ["OutputDirectory"] = "Output Directory",
        ["OutputDirectoryWatermark"] = "Extract destination",
        ["ChmodMode"] = "Chmod Mode",
        ["RecursiveChmod"] = "Recursive chmod",
        ["DirectoryListing"] = "Directory Listing",
        ["Name"] = "Name",
        ["Inode"] = "Inode",
        ["Type"] = "Type",
        ["SuperblockInformation"] = "Superblock Information",

        // Maintenance
        ["TuneFilesystem"] = "Tune Filesystem (tunefs)",
        ["NewVolumeName"] = "New volume name",
        ["PrintOnly"] = "Print Only (no changes)",
        ["EnableSoftUpdates"] = "Enable Soft Updates",
        ["EnableSUJournaling"] = "Enable SU Journaling",
        ["TuneButton"] = "Tune Filesystem",
        ["GrowFilesystem"] = "Grow Filesystem (growfs)",
        ["NewSizeMB"] = "New Size (MB)",
        ["GrowButton"] = "Grow Filesystem",
        ["CheckFilesystem"] = "Check Filesystem (fsck)",
        ["PreenAutoFix"] = "Preen (auto-fix)",
        ["DebugOutput"] = "Debug output",
        ["CheckButton"] = "Check Filesystem",

        // Device & Mount
        ["DeviceMountNotice"] = "Note: Device and mount operations are only available on Windows with the Dokan driver installed.",
        ["DeviceInformation"] = "Device Information",
        ["DevicePath"] = "Device Path",
        ["ShowInfo"] = "Show Info",
        ["MountFilesystem"] = "Mount Filesystem",
        ["DriveLetter"] = "Drive Letter",
        ["ReadWriteMode"] = "Read/Write mode",
        ["Mount"] = "Mount",
        ["UnmountFilesystem"] = "Unmount Filesystem",
        ["Unmount"] = "Unmount",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 Quick Create",
        ["PS5Description"] = "Create a UFS2 filesystem image from a directory for PS5 compatibility.",
        ["PS5InputDirectory"] = "Input Directory",
        ["PS5InputDirectoryWatermark"] = "Path to directory with files to include in the image",
        ["PS5InputDirectoryHint"] = "Select the directory whose contents will populate the PS5 UFS2 image.",
        ["PS5Filename"] = "Output Filename",
        ["PS5FilenameWatermark"] = "Path to output .img file (e.g., ps5_image.img)",
        ["PS5Preset"] = "Configuration",
        ["PS5UseMakefs"] = "Use makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Use newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Create PS5 Image",
        ["PS5ErrorInputDirectory"] = "Please specify an input directory.",
        ["PS5ErrorFilename"] = "Please specify an output image file path.",
        ["PS5Success"] = "PS5-compatible UFS2 image created successfully.",
        ["Browse"] = "Browse...",

        // Settings
        ["Language"] = "Language",
        ["LanguageDescription"] = "Select the display language for the application.",
        ["SettingsTitle"] = "Application Settings",
        ["CurrentLanguage"] = "Current Language",
    };

    private static Dictionary<string, string> GetFrenchStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Créer, inspecter et gérer des images de systèmes de fichiers UFS1/UFS2",
        ["OutputLog"] = "Journal de sortie",
        ["Clear"] = "Effacer",
        ["Detach"] = "Détacher",

        // Tab Headers
        ["TabCreateFilesystem"] = "Créer un système de fichiers",
        ["TabFilesystemOperations"] = "Opérations sur le système de fichiers",
        ["TabMaintenance"] = "Maintenance",
        ["TabDeviceMount"] = "Périphérique et montage",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Paramètres",

        // Create Filesystem
        ["ImageFile"] = "Fichier image",
        ["ImagePathWatermark"] = "Chemin vers le fichier .img de sortie",
        ["ImagePathHint"] = "Ou remplir via le répertoire d'entrée ci-dessous pour créer à partir de fichiers existants.",
        ["FilesystemOptions"] = "Options du système de fichiers",
        ["FilesystemFormat"] = "Format du système de fichiers",
        ["BlockSize"] = "Taille de bloc",
        ["FragmentSize"] = "Taille de fragment",
        ["SectorSize"] = "Taille de secteur",
        ["VolumeName"] = "Nom du volume",
        ["VolumeNameWatermark"] = "Étiquette de volume optionnelle",
        ["MinFreePercent"] = "% libre min.",
        ["Optimization"] = "Optimisation",
        ["BytesPerInode"] = "Octets par inode",
        ["BytesPerInodeWatermark"] = "0 = auto",
        ["ImageSizeMB"] = "Taille de l'image (Mo)",
        ["InputDirectory"] = "Répertoire d'entrée (makefs)",
        ["InputDirectoryWatermark"] = "Chemin vers le répertoire dont le contenu remplit l'image",
        ["InputDirectoryHint"] = "Si défini, la taille de l'image est déterminée automatiquement à partir du contenu du répertoire.",
        ["Flags"] = "Options",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "Journalisation SU",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Effacer le contenu",
        ["DryRun"] = "Exécution à blanc",
        ["CreateFilesystem"] = "Créer le système de fichiers",

        // Filesystem Operations
        ["ImagePath"] = "Chemin de l'image",
        ["ImagePathFSWatermark"] = "Chemin vers le fichier .img",
        ["FSPath"] = "Chemin FS",
        ["Info"] = "Infos",
        ["ListLS"] = "Lister (LS)",
        ["Extract"] = "Extraire",
        ["Add"] = "Ajouter",
        ["Delete"] = "Supprimer",
        ["Replace"] = "Remplacer",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Chemin local",
        ["LocalPathWatermark"] = "Fichier/répertoire local pour Ajouter ou Remplacer",
        ["OutputDirectory"] = "Répertoire de sortie",
        ["OutputDirectoryWatermark"] = "Destination d'extraction",
        ["ChmodMode"] = "Mode Chmod",
        ["RecursiveChmod"] = "Chmod récursif",
        ["DirectoryListing"] = "Liste du répertoire",
        ["Name"] = "Nom",
        ["Inode"] = "Inode",
        ["Type"] = "Type",
        ["SuperblockInformation"] = "Informations du superbloc",

        // Maintenance
        ["TuneFilesystem"] = "Régler le système de fichiers (tunefs)",
        ["NewVolumeName"] = "Nouveau nom de volume",
        ["PrintOnly"] = "Afficher uniquement (aucune modification)",
        ["EnableSoftUpdates"] = "Activer Soft Updates",
        ["EnableSUJournaling"] = "Activer la journalisation SU",
        ["TuneButton"] = "Régler le système de fichiers",
        ["GrowFilesystem"] = "Agrandir le système de fichiers (growfs)",
        ["NewSizeMB"] = "Nouvelle taille (Mo)",
        ["GrowButton"] = "Agrandir le système de fichiers",
        ["CheckFilesystem"] = "Vérifier le système de fichiers (fsck)",
        ["PreenAutoFix"] = "Preen (correction auto)",
        ["DebugOutput"] = "Sortie de débogage",
        ["CheckButton"] = "Vérifier le système de fichiers",

        // Device & Mount
        ["DeviceMountNotice"] = "Note : Les opérations de périphérique et de montage ne sont disponibles que sous Windows avec le pilote Dokan installé.",
        ["DeviceInformation"] = "Informations sur le périphérique",
        ["DevicePath"] = "Chemin du périphérique",
        ["ShowInfo"] = "Afficher les infos",
        ["MountFilesystem"] = "Monter le système de fichiers",
        ["DriveLetter"] = "Lettre de lecteur",
        ["ReadWriteMode"] = "Mode lecture/écriture",
        ["Mount"] = "Monter",
        ["UnmountFilesystem"] = "Démonter le système de fichiers",
        ["Unmount"] = "Démonter",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "Création rapide PS5",
        ["PS5Description"] = "Créer une image de système de fichiers UFS2 à partir d'un répertoire pour la compatibilité PS5.",
        ["PS5InputDirectory"] = "Répertoire d'entrée",
        ["PS5InputDirectoryWatermark"] = "Chemin vers le répertoire avec les fichiers à inclure dans l'image",
        ["PS5InputDirectoryHint"] = "Sélectionnez le répertoire dont le contenu remplira l'image UFS2 PS5.",
        ["PS5Filename"] = "Nom du fichier de sortie",
        ["PS5FilenameWatermark"] = "Chemin vers le fichier .img de sortie (ex. : ps5_image.img)",
        ["PS5Preset"] = "Configuration",
        ["PS5UseMakefs"] = "Utiliser makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Utiliser newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Créer l'image PS5",
        ["PS5ErrorInputDirectory"] = "Veuillez spécifier un répertoire d'entrée.",
        ["PS5ErrorFilename"] = "Veuillez spécifier un chemin de fichier image de sortie.",
        ["PS5Success"] = "Image UFS2 compatible PS5 créée avec succès.",
        ["Browse"] = "Parcourir...",

        // Settings
        ["Language"] = "Langue",
        ["LanguageDescription"] = "Sélectionnez la langue d'affichage de l'application.",
        ["SettingsTitle"] = "Paramètres de l'application",
        ["CurrentLanguage"] = "Langue actuelle",
    };

    private static Dictionary<string, string> GetSpanishStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Crear, inspeccionar y gestionar imágenes de sistemas de archivos UFS1/UFS2",
        ["OutputLog"] = "Registro de salida",
        ["Clear"] = "Limpiar",
        ["Detach"] = "Separar",

        // Tab Headers
        ["TabCreateFilesystem"] = "Crear sistema de archivos",
        ["TabFilesystemOperations"] = "Operaciones del sistema de archivos",
        ["TabMaintenance"] = "Mantenimiento",
        ["TabDeviceMount"] = "Dispositivo y montaje",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Configuración",

        // Create Filesystem
        ["ImageFile"] = "Archivo de imagen",
        ["ImagePathWatermark"] = "Ruta al archivo .img de salida",
        ["ImagePathHint"] = "O completar mediante el directorio de entrada a continuación para crear a partir de archivos existentes.",
        ["FilesystemOptions"] = "Opciones del sistema de archivos",
        ["FilesystemFormat"] = "Formato del sistema de archivos",
        ["BlockSize"] = "Tamaño de bloque",
        ["FragmentSize"] = "Tamaño de fragmento",
        ["SectorSize"] = "Tamaño de sector",
        ["VolumeName"] = "Nombre del volumen",
        ["VolumeNameWatermark"] = "Etiqueta de volumen opcional",
        ["MinFreePercent"] = "% libre mín.",
        ["Optimization"] = "Optimización",
        ["BytesPerInode"] = "Bytes por inodo",
        ["BytesPerInodeWatermark"] = "0 = auto",
        ["ImageSizeMB"] = "Tamaño de imagen (MB)",
        ["InputDirectory"] = "Directorio de entrada (makefs)",
        ["InputDirectoryWatermark"] = "Ruta al directorio cuyo contenido llena la imagen",
        ["InputDirectoryHint"] = "Si se establece, el tamaño de la imagen se determina automáticamente a partir del contenido del directorio.",
        ["Flags"] = "Opciones",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "Journaling SU",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Borrar contenido",
        ["DryRun"] = "Ejecución en seco",
        ["CreateFilesystem"] = "Crear sistema de archivos",

        // Filesystem Operations
        ["ImagePath"] = "Ruta de imagen",
        ["ImagePathFSWatermark"] = "Ruta al archivo .img",
        ["FSPath"] = "Ruta FS",
        ["Info"] = "Info",
        ["ListLS"] = "Listar (LS)",
        ["Extract"] = "Extraer",
        ["Add"] = "Agregar",
        ["Delete"] = "Eliminar",
        ["Replace"] = "Reemplazar",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Ruta local",
        ["LocalPathWatermark"] = "Archivo/directorio local para Agregar o Reemplazar",
        ["OutputDirectory"] = "Directorio de salida",
        ["OutputDirectoryWatermark"] = "Destino de extracción",
        ["ChmodMode"] = "Modo Chmod",
        ["RecursiveChmod"] = "Chmod recursivo",
        ["DirectoryListing"] = "Listado de directorio",
        ["Name"] = "Nombre",
        ["Inode"] = "Inodo",
        ["Type"] = "Tipo",
        ["SuperblockInformation"] = "Información del superbloque",

        // Maintenance
        ["TuneFilesystem"] = "Ajustar sistema de archivos (tunefs)",
        ["NewVolumeName"] = "Nuevo nombre de volumen",
        ["PrintOnly"] = "Solo mostrar (sin cambios)",
        ["EnableSoftUpdates"] = "Habilitar Soft Updates",
        ["EnableSUJournaling"] = "Habilitar Journaling SU",
        ["TuneButton"] = "Ajustar sistema de archivos",
        ["GrowFilesystem"] = "Ampliar sistema de archivos (growfs)",
        ["NewSizeMB"] = "Nuevo tamaño (MB)",
        ["GrowButton"] = "Ampliar sistema de archivos",
        ["CheckFilesystem"] = "Verificar sistema de archivos (fsck)",
        ["PreenAutoFix"] = "Preen (corrección auto.)",
        ["DebugOutput"] = "Salida de depuración",
        ["CheckButton"] = "Verificar sistema de archivos",

        // Device & Mount
        ["DeviceMountNotice"] = "Nota: Las operaciones de dispositivo y montaje solo están disponibles en Windows con el controlador Dokan instalado.",
        ["DeviceInformation"] = "Información del dispositivo",
        ["DevicePath"] = "Ruta del dispositivo",
        ["ShowInfo"] = "Mostrar info",
        ["MountFilesystem"] = "Montar sistema de archivos",
        ["DriveLetter"] = "Letra de unidad",
        ["ReadWriteMode"] = "Modo lectura/escritura",
        ["Mount"] = "Montar",
        ["UnmountFilesystem"] = "Desmontar sistema de archivos",
        ["Unmount"] = "Desmontar",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "Creación rápida PS5",
        ["PS5Description"] = "Crear una imagen de sistema de archivos UFS2 desde un directorio para compatibilidad con PS5.",
        ["PS5InputDirectory"] = "Directorio de entrada",
        ["PS5InputDirectoryWatermark"] = "Ruta al directorio con archivos para incluir en la imagen",
        ["PS5InputDirectoryHint"] = "Seleccione el directorio cuyo contenido llenará la imagen UFS2 PS5.",
        ["PS5Filename"] = "Nombre del archivo de salida",
        ["PS5FilenameWatermark"] = "Ruta al archivo .img de salida (ej.: ps5_image.img)",
        ["PS5Preset"] = "Configuración",
        ["PS5UseMakefs"] = "Usar makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Usar newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Crear imagen PS5",
        ["PS5ErrorInputDirectory"] = "Especifique un directorio de entrada.",
        ["PS5ErrorFilename"] = "Especifique una ruta de archivo de imagen de salida.",
        ["PS5Success"] = "Imagen UFS2 compatible con PS5 creada exitosamente.",
        ["Browse"] = "Examinar...",

        // Settings
        ["Language"] = "Idioma",
        ["LanguageDescription"] = "Seleccione el idioma de visualización de la aplicación.",
        ["SettingsTitle"] = "Configuración de la aplicación",
        ["CurrentLanguage"] = "Idioma actual",
    };

    private static Dictionary<string, string> GetGermanStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "UFS1/UFS2-Dateisystemabbilder erstellen, inspizieren und verwalten",
        ["OutputLog"] = "Ausgabeprotokoll",
        ["Clear"] = "Löschen",
        ["Detach"] = "Abtrennen",

        // Tab Headers
        ["TabCreateFilesystem"] = "Dateisystem erstellen",
        ["TabFilesystemOperations"] = "Dateisystemoperationen",
        ["TabMaintenance"] = "Wartung",
        ["TabDeviceMount"] = "Gerät & Einbindung",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Einstellungen",

        // Create Filesystem
        ["ImageFile"] = "Abbilddatei",
        ["ImagePathWatermark"] = "Pfad zur Ausgabe-.img-Datei",
        ["ImagePathHint"] = "Oder über das Eingabeverzeichnis unten befüllen, um aus vorhandenen Dateien zu erstellen.",
        ["FilesystemOptions"] = "Dateisystemoptionen",
        ["FilesystemFormat"] = "Dateisystemformat",
        ["BlockSize"] = "Blockgröße",
        ["FragmentSize"] = "Fragmentgröße",
        ["SectorSize"] = "Sektorgröße",
        ["VolumeName"] = "Datenträgername",
        ["VolumeNameWatermark"] = "Optionale Datenträgerbezeichnung",
        ["MinFreePercent"] = "Min. frei %",
        ["Optimization"] = "Optimierung",
        ["BytesPerInode"] = "Bytes pro Inode",
        ["BytesPerInodeWatermark"] = "0 = auto",
        ["ImageSizeMB"] = "Abbildgröße (MB)",
        ["InputDirectory"] = "Eingabeverzeichnis (makefs)",
        ["InputDirectoryWatermark"] = "Pfad zum Verzeichnis, dessen Inhalt das Abbild füllt",
        ["InputDirectoryHint"] = "Falls gesetzt, wird die Abbildgröße automatisch aus dem Verzeichnisinhalt bestimmt.",
        ["Flags"] = "Optionen",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU-Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Inhalt löschen",
        ["DryRun"] = "Probelauf",
        ["CreateFilesystem"] = "Dateisystem erstellen",

        // Filesystem Operations
        ["ImagePath"] = "Abbildpfad",
        ["ImagePathFSWatermark"] = "Pfad zur .img-Datei",
        ["FSPath"] = "FS-Pfad",
        ["Info"] = "Info",
        ["ListLS"] = "Auflisten (LS)",
        ["Extract"] = "Extrahieren",
        ["Add"] = "Hinzufügen",
        ["Delete"] = "Löschen",
        ["Replace"] = "Ersetzen",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Lokaler Pfad",
        ["LocalPathWatermark"] = "Lokale Datei/Verzeichnis zum Hinzufügen oder Ersetzen",
        ["OutputDirectory"] = "Ausgabeverzeichnis",
        ["OutputDirectoryWatermark"] = "Extraktionsziel",
        ["ChmodMode"] = "Chmod-Modus",
        ["RecursiveChmod"] = "Rekursives Chmod",
        ["DirectoryListing"] = "Verzeichnisliste",
        ["Name"] = "Name",
        ["Inode"] = "Inode",
        ["Type"] = "Typ",
        ["SuperblockInformation"] = "Superblock-Informationen",

        // Maintenance
        ["TuneFilesystem"] = "Dateisystem anpassen (tunefs)",
        ["NewVolumeName"] = "Neuer Datenträgername",
        ["PrintOnly"] = "Nur anzeigen (keine Änderungen)",
        ["EnableSoftUpdates"] = "Soft Updates aktivieren",
        ["EnableSUJournaling"] = "SU-Journaling aktivieren",
        ["TuneButton"] = "Dateisystem anpassen",
        ["GrowFilesystem"] = "Dateisystem vergrößern (growfs)",
        ["NewSizeMB"] = "Neue Größe (MB)",
        ["GrowButton"] = "Dateisystem vergrößern",
        ["CheckFilesystem"] = "Dateisystem prüfen (fsck)",
        ["PreenAutoFix"] = "Preen (Auto-Reparatur)",
        ["DebugOutput"] = "Debug-Ausgabe",
        ["CheckButton"] = "Dateisystem prüfen",

        // Device & Mount
        ["DeviceMountNotice"] = "Hinweis: Geräte- und Einbindungsoperationen sind nur unter Windows mit installiertem Dokan-Treiber verfügbar.",
        ["DeviceInformation"] = "Geräteinformationen",
        ["DevicePath"] = "Gerätepfad",
        ["ShowInfo"] = "Info anzeigen",
        ["MountFilesystem"] = "Dateisystem einbinden",
        ["DriveLetter"] = "Laufwerksbuchstabe",
        ["ReadWriteMode"] = "Lese-/Schreibmodus",
        ["Mount"] = "Einbinden",
        ["UnmountFilesystem"] = "Dateisystem aushängen",
        ["Unmount"] = "Aushängen",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5-Schnellerstellung",
        ["PS5Description"] = "Ein UFS2-Dateisystemabbild aus einem Verzeichnis für PS5-Kompatibilität erstellen.",
        ["PS5InputDirectory"] = "Eingabeverzeichnis",
        ["PS5InputDirectoryWatermark"] = "Pfad zum Verzeichnis mit Dateien, die in das Abbild aufgenommen werden",
        ["PS5InputDirectoryHint"] = "Wählen Sie das Verzeichnis, dessen Inhalt das PS5 UFS2-Abbild füllt.",
        ["PS5Filename"] = "Ausgabedateiname",
        ["PS5FilenameWatermark"] = "Pfad zur Ausgabe-.img-Datei (z.B. ps5_image.img)",
        ["PS5Preset"] = "Konfiguration",
        ["PS5UseMakefs"] = "makefs verwenden",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "newfs verwenden",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "PS5-Abbild erstellen",
        ["PS5ErrorInputDirectory"] = "Bitte geben Sie ein Eingabeverzeichnis an.",
        ["PS5ErrorFilename"] = "Bitte geben Sie einen Pfad für die Ausgabe-Abbilddatei an.",
        ["PS5Success"] = "PS5-kompatibles UFS2-Abbild erfolgreich erstellt.",
        ["Browse"] = "Durchsuchen...",

        // Settings
        ["Language"] = "Sprache",
        ["LanguageDescription"] = "Wählen Sie die Anzeigesprache der Anwendung.",
        ["SettingsTitle"] = "Anwendungseinstellungen",
        ["CurrentLanguage"] = "Aktuelle Sprache",
    };

    private static Dictionary<string, string> GetChineseStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 工具",
        ["AppSubtitle"] = "创建、检查和管理 UFS1/UFS2 文件系统映像",
        ["OutputLog"] = "输出日志",
        ["Clear"] = "清除",
        ["Detach"] = "分离",

        // Tab Headers
        ["TabCreateFilesystem"] = "创建文件系统",
        ["TabFilesystemOperations"] = "文件系统操作",
        ["TabMaintenance"] = "维护",
        ["TabDeviceMount"] = "设备和挂载",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "设置",

        // Create Filesystem
        ["ImageFile"] = "映像文件",
        ["ImagePathWatermark"] = "输出 .img 文件的路径",
        ["ImagePathHint"] = "或通过下面的输入目录填充，以从现有文件创建。",
        ["FilesystemOptions"] = "文件系统选项",
        ["FilesystemFormat"] = "文件系统格式",
        ["BlockSize"] = "块大小",
        ["FragmentSize"] = "片段大小",
        ["SectorSize"] = "扇区大小",
        ["VolumeName"] = "卷名",
        ["VolumeNameWatermark"] = "可选卷标",
        ["MinFreePercent"] = "最小空闲 %",
        ["Optimization"] = "优化",
        ["BytesPerInode"] = "每个 Inode 字节数",
        ["BytesPerInodeWatermark"] = "0 = 自动",
        ["ImageSizeMB"] = "映像大小 (MB)",
        ["InputDirectory"] = "输入目录 (makefs)",
        ["InputDirectoryWatermark"] = "内容填充映像的目录路径",
        ["InputDirectoryHint"] = "如果设置，映像大小将根据目录内容自动确定。",
        ["Flags"] = "选项",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU 日志",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "擦除内容",
        ["DryRun"] = "模拟运行",
        ["CreateFilesystem"] = "创建文件系统",

        // Filesystem Operations
        ["ImagePath"] = "映像路径",
        ["ImagePathFSWatermark"] = ".img 文件的路径",
        ["FSPath"] = "FS 路径",
        ["Info"] = "信息",
        ["ListLS"] = "列表 (LS)",
        ["Extract"] = "提取",
        ["Add"] = "添加",
        ["Delete"] = "删除",
        ["Replace"] = "替换",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "本地路径",
        ["LocalPathWatermark"] = "用于添加或替换的本地文件/目录",
        ["OutputDirectory"] = "输出目录",
        ["OutputDirectoryWatermark"] = "提取目标",
        ["ChmodMode"] = "Chmod 模式",
        ["RecursiveChmod"] = "递归 chmod",
        ["DirectoryListing"] = "目录列表",
        ["Name"] = "名称",
        ["Inode"] = "Inode",
        ["Type"] = "类型",
        ["SuperblockInformation"] = "超级块信息",

        // Maintenance
        ["TuneFilesystem"] = "调整文件系统 (tunefs)",
        ["NewVolumeName"] = "新卷名",
        ["PrintOnly"] = "仅显示（不修改）",
        ["EnableSoftUpdates"] = "启用 Soft Updates",
        ["EnableSUJournaling"] = "启用 SU 日志",
        ["TuneButton"] = "调整文件系统",
        ["GrowFilesystem"] = "扩展文件系统 (growfs)",
        ["NewSizeMB"] = "新大小 (MB)",
        ["GrowButton"] = "扩展文件系统",
        ["CheckFilesystem"] = "检查文件系统 (fsck)",
        ["PreenAutoFix"] = "Preen（自动修复）",
        ["DebugOutput"] = "调试输出",
        ["CheckButton"] = "检查文件系统",

        // Device & Mount
        ["DeviceMountNotice"] = "注意：设备和挂载操作仅在安装了 Dokan 驱动程序的 Windows 上可用。",
        ["DeviceInformation"] = "设备信息",
        ["DevicePath"] = "设备路径",
        ["ShowInfo"] = "显示信息",
        ["MountFilesystem"] = "挂载文件系统",
        ["DriveLetter"] = "驱动器号",
        ["ReadWriteMode"] = "读/写模式",
        ["Mount"] = "挂载",
        ["UnmountFilesystem"] = "卸载文件系统",
        ["Unmount"] = "卸载",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 快速创建",
        ["PS5Description"] = "从目录创建 PS5 兼容的 UFS2 文件系统映像。",
        ["PS5InputDirectory"] = "输入目录",
        ["PS5InputDirectoryWatermark"] = "包含要添加到映像中的文件的目录路径",
        ["PS5InputDirectoryHint"] = "选择其内容将填充 PS5 UFS2 映像的目录。",
        ["PS5Filename"] = "输出文件名",
        ["PS5FilenameWatermark"] = "输出 .img 文件的路径（例如：ps5_image.img）",
        ["PS5Preset"] = "配置",
        ["PS5UseMakefs"] = "使用 makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "使用 newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "创建 PS5 映像",
        ["PS5ErrorInputDirectory"] = "请指定输入目录。",
        ["PS5ErrorFilename"] = "请指定输出映像文件路径。",
        ["PS5Success"] = "PS5 兼容 UFS2 映像创建成功。",
        ["Browse"] = "浏览...",

        // Settings
        ["Language"] = "语言",
        ["LanguageDescription"] = "选择应用程序的显示语言。",
        ["SettingsTitle"] = "应用程序设置",
        ["CurrentLanguage"] = "当前语言",
    };

    private static Dictionary<string, string> GetJapaneseStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 ツール",
        ["AppSubtitle"] = "UFS1/UFS2 ファイルシステムイメージの作成、検査、管理",
        ["OutputLog"] = "出力ログ",
        ["Clear"] = "クリア",
        ["Detach"] = "切り離す",

        // Tab Headers
        ["TabCreateFilesystem"] = "ファイルシステム作成",
        ["TabFilesystemOperations"] = "ファイルシステム操作",
        ["TabMaintenance"] = "メンテナンス",
        ["TabDeviceMount"] = "デバイスとマウント",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "設定",

        // Create Filesystem
        ["ImageFile"] = "イメージファイル",
        ["ImagePathWatermark"] = "出力 .img ファイルのパス",
        ["ImagePathHint"] = "または、下記の入力ディレクトリから既存ファイルで作成することもできます。",
        ["FilesystemOptions"] = "ファイルシステムオプション",
        ["FilesystemFormat"] = "ファイルシステム形式",
        ["BlockSize"] = "ブロックサイズ",
        ["FragmentSize"] = "フラグメントサイズ",
        ["SectorSize"] = "セクタサイズ",
        ["VolumeName"] = "ボリューム名",
        ["VolumeNameWatermark"] = "任意のボリュームラベル",
        ["MinFreePercent"] = "最小空き %",
        ["Optimization"] = "最適化",
        ["BytesPerInode"] = "Inode あたりのバイト数",
        ["BytesPerInodeWatermark"] = "0 = 自動",
        ["ImageSizeMB"] = "イメージサイズ (MB)",
        ["InputDirectory"] = "入力ディレクトリ (makefs)",
        ["InputDirectoryWatermark"] = "イメージに配置するコンテンツのディレクトリパス",
        ["InputDirectoryHint"] = "設定すると、イメージサイズはディレクトリの内容から自動的に決定されます。",
        ["Flags"] = "オプション",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU ジャーナリング",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "内容を消去",
        ["DryRun"] = "ドライラン",
        ["CreateFilesystem"] = "ファイルシステムを作成",

        // Filesystem Operations
        ["ImagePath"] = "イメージパス",
        ["ImagePathFSWatermark"] = ".img ファイルのパス",
        ["FSPath"] = "FS パス",
        ["Info"] = "情報",
        ["ListLS"] = "一覧 (LS)",
        ["Extract"] = "抽出",
        ["Add"] = "追加",
        ["Delete"] = "削除",
        ["Replace"] = "置換",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "ローカルパス",
        ["LocalPathWatermark"] = "追加または置換用のローカルファイル/ディレクトリ",
        ["OutputDirectory"] = "出力ディレクトリ",
        ["OutputDirectoryWatermark"] = "抽出先",
        ["ChmodMode"] = "Chmod モード",
        ["RecursiveChmod"] = "再帰的 chmod",
        ["DirectoryListing"] = "ディレクトリ一覧",
        ["Name"] = "名前",
        ["Inode"] = "Inode",
        ["Type"] = "種類",
        ["SuperblockInformation"] = "スーパーブロック情報",

        // Maintenance
        ["TuneFilesystem"] = "ファイルシステム調整 (tunefs)",
        ["NewVolumeName"] = "新しいボリューム名",
        ["PrintOnly"] = "表示のみ（変更なし）",
        ["EnableSoftUpdates"] = "Soft Updates を有効化",
        ["EnableSUJournaling"] = "SU ジャーナリングを有効化",
        ["TuneButton"] = "ファイルシステムを調整",
        ["GrowFilesystem"] = "ファイルシステム拡張 (growfs)",
        ["NewSizeMB"] = "新しいサイズ (MB)",
        ["GrowButton"] = "ファイルシステムを拡張",
        ["CheckFilesystem"] = "ファイルシステム検査 (fsck)",
        ["PreenAutoFix"] = "Preen（自動修復）",
        ["DebugOutput"] = "デバッグ出力",
        ["CheckButton"] = "ファイルシステムを検査",

        // Device & Mount
        ["DeviceMountNotice"] = "注意：デバイスおよびマウント操作は、Dokan ドライバがインストールされた Windows でのみ利用可能です。",
        ["DeviceInformation"] = "デバイス情報",
        ["DevicePath"] = "デバイスパス",
        ["ShowInfo"] = "情報を表示",
        ["MountFilesystem"] = "ファイルシステムをマウント",
        ["DriveLetter"] = "ドライブレター",
        ["ReadWriteMode"] = "読み取り/書き込みモード",
        ["Mount"] = "マウント",
        ["UnmountFilesystem"] = "ファイルシステムのアンマウント",
        ["Unmount"] = "アンマウント",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 クイック作成",
        ["PS5Description"] = "PS5 互換の UFS2 ファイルシステムイメージをディレクトリから作成します。",
        ["PS5InputDirectory"] = "入力ディレクトリ",
        ["PS5InputDirectoryWatermark"] = "イメージに含めるファイルがあるディレクトリのパス",
        ["PS5InputDirectoryHint"] = "PS5 UFS2 イメージに配置するコンテンツのディレクトリを選択してください。",
        ["PS5Filename"] = "出力ファイル名",
        ["PS5FilenameWatermark"] = "出力 .img ファイルのパス（例：ps5_image.img）",
        ["PS5Preset"] = "構成",
        ["PS5UseMakefs"] = "makefs を使用",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "newfs を使用",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "PS5 イメージを作成",
        ["PS5ErrorInputDirectory"] = "入力ディレクトリを指定してください。",
        ["PS5ErrorFilename"] = "出力イメージファイルのパスを指定してください。",
        ["PS5Success"] = "PS5 互換 UFS2 イメージが正常に作成されました。",
        ["Browse"] = "参照...",

        // Settings
        ["Language"] = "言語",
        ["LanguageDescription"] = "アプリケーションの表示言語を選択してください。",
        ["SettingsTitle"] = "アプリケーション設定",
        ["CurrentLanguage"] = "現在の言語",
    };

    private static Dictionary<string, string> GetArabicStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "إنشاء وفحص وإدارة صور أنظمة ملفات UFS1/UFS2",
        ["OutputLog"] = "سجل المخرجات",
        ["Clear"] = "مسح",
        ["Detach"] = "فصل",

        // Tab Headers
        ["TabCreateFilesystem"] = "إنشاء نظام ملفات",
        ["TabFilesystemOperations"] = "عمليات نظام الملفات",
        ["TabMaintenance"] = "الصيانة",
        ["TabDeviceMount"] = "الجهاز والتحميل",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "الإعدادات",

        // Create Filesystem
        ["ImageFile"] = "ملف الصورة",
        ["ImagePathWatermark"] = "مسار ملف .img الناتج",
        ["ImagePathHint"] = "أو قم بالتعبئة عبر دليل الإدخال أدناه للإنشاء من ملفات موجودة.",
        ["FilesystemOptions"] = "خيارات نظام الملفات",
        ["FilesystemFormat"] = "تنسيق نظام الملفات",
        ["BlockSize"] = "حجم الكتلة",
        ["FragmentSize"] = "حجم الجزء",
        ["SectorSize"] = "حجم القطاع",
        ["VolumeName"] = "اسم المجلد",
        ["VolumeNameWatermark"] = "تسمية مجلد اختيارية",
        ["MinFreePercent"] = "الحد الأدنى للمساحة الحرة %",
        ["Optimization"] = "التحسين",
        ["BytesPerInode"] = "بايت لكل Inode",
        ["BytesPerInodeWatermark"] = "0 = تلقائي",
        ["ImageSizeMB"] = "حجم الصورة (ميغابايت)",
        ["InputDirectory"] = "دليل الإدخال (makefs)",
        ["InputDirectoryWatermark"] = "مسار الدليل الذي يملأ محتواه الصورة",
        ["InputDirectoryHint"] = "إذا تم تعيينه، يتم تحديد حجم الصورة تلقائيًا من محتويات الدليل.",
        ["Flags"] = "الخيارات",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "مسح المحتويات",
        ["DryRun"] = "تشغيل تجريبي",
        ["CreateFilesystem"] = "إنشاء نظام ملفات",

        // Filesystem Operations
        ["ImagePath"] = "مسار الصورة",
        ["ImagePathFSWatermark"] = "مسار ملف .img",
        ["FSPath"] = "مسار نظام الملفات",
        ["Info"] = "معلومات",
        ["ListLS"] = "قائمة (LS)",
        ["Extract"] = "استخراج",
        ["Add"] = "إضافة",
        ["Delete"] = "حذف",
        ["Replace"] = "استبدال",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "المسار المحلي",
        ["LocalPathWatermark"] = "ملف/دليل محلي للإضافة أو الاستبدال",
        ["OutputDirectory"] = "دليل المخرجات",
        ["OutputDirectoryWatermark"] = "وجهة الاستخراج",
        ["ChmodMode"] = "وضع Chmod",
        ["RecursiveChmod"] = "Chmod تكراري",
        ["DirectoryListing"] = "قائمة الدليل",
        ["Name"] = "الاسم",
        ["Inode"] = "Inode",
        ["Type"] = "النوع",
        ["SuperblockInformation"] = "معلومات الكتلة الفائقة",

        // Maintenance
        ["TuneFilesystem"] = "ضبط نظام الملفات (tunefs)",
        ["NewVolumeName"] = "اسم المجلد الجديد",
        ["PrintOnly"] = "طباعة فقط (بدون تغييرات)",
        ["EnableSoftUpdates"] = "تفعيل Soft Updates",
        ["EnableSUJournaling"] = "تفعيل SU Journaling",
        ["TuneButton"] = "ضبط نظام الملفات",
        ["GrowFilesystem"] = "توسيع نظام الملفات (growfs)",
        ["NewSizeMB"] = "الحجم الجديد (ميغابايت)",
        ["GrowButton"] = "توسيع نظام الملفات",
        ["CheckFilesystem"] = "فحص نظام الملفات (fsck)",
        ["PreenAutoFix"] = "Preen (إصلاح تلقائي)",
        ["DebugOutput"] = "مخرجات التصحيح",
        ["CheckButton"] = "فحص نظام الملفات",

        // Device & Mount
        ["DeviceMountNotice"] = "ملاحظة: عمليات الجهاز والتحميل متاحة فقط على Windows مع تثبيت برنامج تشغيل Dokan.",
        ["DeviceInformation"] = "معلومات الجهاز",
        ["DevicePath"] = "مسار الجهاز",
        ["ShowInfo"] = "عرض المعلومات",
        ["MountFilesystem"] = "تحميل نظام الملفات",
        ["DriveLetter"] = "حرف محرك الأقراص",
        ["ReadWriteMode"] = "وضع القراءة/الكتابة",
        ["Mount"] = "تحميل",
        ["UnmountFilesystem"] = "إلغاء تحميل نظام الملفات",
        ["Unmount"] = "إلغاء التحميل",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "إنشاء سريع PS5",
        ["PS5Description"] = "إنشاء صورة نظام ملفات UFS2 من دليل للتوافق مع PS5.",
        ["PS5InputDirectory"] = "دليل الإدخال",
        ["PS5InputDirectoryWatermark"] = "مسار الدليل الذي يحتوي على الملفات المراد تضمينها في الصورة",
        ["PS5InputDirectoryHint"] = "حدد الدليل الذي سيملأ محتواه صورة UFS2 الخاصة بـ PS5.",
        ["PS5Filename"] = "اسم ملف المخرجات",
        ["PS5FilenameWatermark"] = "مسار ملف .img الناتج (مثال: ps5_image.img)",
        ["PS5Preset"] = "الإعدادات",
        ["PS5UseMakefs"] = "استخدام makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "استخدام newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "إنشاء صورة PS5",
        ["PS5ErrorInputDirectory"] = "يرجى تحديد دليل الإدخال.",
        ["PS5ErrorFilename"] = "يرجى تحديد مسار ملف الصورة الناتج.",
        ["PS5Success"] = "تم إنشاء صورة UFS2 المتوافقة مع PS5 بنجاح.",
        ["Browse"] = "استعراض...",

        // Settings
        ["Language"] = "اللغة",
        ["LanguageDescription"] = "حدد لغة العرض للتطبيق.",
        ["SettingsTitle"] = "إعدادات التطبيق",
        ["CurrentLanguage"] = "اللغة الحالية",
    };

    private static Dictionary<string, string> GetRussianStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Создание, просмотр и управление образами файловых систем UFS1/UFS2",
        ["OutputLog"] = "Журнал вывода",
        ["Clear"] = "Очистить",
        ["Detach"] = "Отсоединить",

        // Tab Headers
        ["TabCreateFilesystem"] = "Создать файловую систему",
        ["TabFilesystemOperations"] = "Операции с файловой системой",
        ["TabMaintenance"] = "Обслуживание",
        ["TabDeviceMount"] = "Устройство и монтирование",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Настройки",

        // Create Filesystem
        ["ImageFile"] = "Файл образа",
        ["ImagePathWatermark"] = "Путь к выходному файлу .img",
        ["ImagePathHint"] = "Или заполните через каталог ввода ниже для создания из существующих файлов.",
        ["FilesystemOptions"] = "Параметры файловой системы",
        ["FilesystemFormat"] = "Формат файловой системы",
        ["BlockSize"] = "Размер блока",
        ["FragmentSize"] = "Размер фрагмента",
        ["SectorSize"] = "Размер сектора",
        ["VolumeName"] = "Имя тома",
        ["VolumeNameWatermark"] = "Необязательная метка тома",
        ["MinFreePercent"] = "Мин. свободно %",
        ["Optimization"] = "Оптимизация",
        ["BytesPerInode"] = "Байт на Inode",
        ["BytesPerInodeWatermark"] = "0 = авто",
        ["ImageSizeMB"] = "Размер образа (МБ)",
        ["InputDirectory"] = "Входной каталог (makefs)",
        ["InputDirectoryWatermark"] = "Путь к каталогу, содержимое которого заполнит образ",
        ["InputDirectoryHint"] = "Если указан, размер образа определяется автоматически по содержимому каталога.",
        ["Flags"] = "Флаги",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Стереть содержимое",
        ["DryRun"] = "Пробный запуск",
        ["CreateFilesystem"] = "Создать файловую систему",

        // Filesystem Operations
        ["ImagePath"] = "Путь к образу",
        ["ImagePathFSWatermark"] = "Путь к файлу .img",
        ["FSPath"] = "Путь ФС",
        ["Info"] = "Информация",
        ["ListLS"] = "Список (LS)",
        ["Extract"] = "Извлечь",
        ["Add"] = "Добавить",
        ["Delete"] = "Удалить",
        ["Replace"] = "Заменить",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Локальный путь",
        ["LocalPathWatermark"] = "Локальный файл/каталог для добавления или замены",
        ["OutputDirectory"] = "Выходной каталог",
        ["OutputDirectoryWatermark"] = "Место назначения извлечения",
        ["ChmodMode"] = "Режим Chmod",
        ["RecursiveChmod"] = "Рекурсивный Chmod",
        ["DirectoryListing"] = "Список каталога",
        ["Name"] = "Имя",
        ["Inode"] = "Inode",
        ["Type"] = "Тип",
        ["SuperblockInformation"] = "Информация о суперблоке",

        // Maintenance
        ["TuneFilesystem"] = "Настройка файловой системы (tunefs)",
        ["NewVolumeName"] = "Новое имя тома",
        ["PrintOnly"] = "Только просмотр (без изменений)",
        ["EnableSoftUpdates"] = "Включить Soft Updates",
        ["EnableSUJournaling"] = "Включить SU Journaling",
        ["TuneButton"] = "Настроить файловую систему",
        ["GrowFilesystem"] = "Расширить файловую систему (growfs)",
        ["NewSizeMB"] = "Новый размер (МБ)",
        ["GrowButton"] = "Расширить файловую систему",
        ["CheckFilesystem"] = "Проверить файловую систему (fsck)",
        ["PreenAutoFix"] = "Preen (автоисправление)",
        ["DebugOutput"] = "Отладочный вывод",
        ["CheckButton"] = "Проверить файловую систему",

        // Device & Mount
        ["DeviceMountNotice"] = "Примечание: операции с устройствами и монтированием доступны только в Windows с установленным драйвером Dokan.",
        ["DeviceInformation"] = "Информация об устройстве",
        ["DevicePath"] = "Путь к устройству",
        ["ShowInfo"] = "Показать информацию",
        ["MountFilesystem"] = "Монтировать файловую систему",
        ["DriveLetter"] = "Буква диска",
        ["ReadWriteMode"] = "Режим чтения/записи",
        ["Mount"] = "Монтировать",
        ["UnmountFilesystem"] = "Размонтировать файловую систему",
        ["Unmount"] = "Размонтировать",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "Быстрое создание PS5",
        ["PS5Description"] = "Создание образа файловой системы UFS2 из каталога для совместимости с PS5.",
        ["PS5InputDirectory"] = "Входной каталог",
        ["PS5InputDirectoryWatermark"] = "Путь к каталогу с файлами для включения в образ",
        ["PS5InputDirectoryHint"] = "Выберите каталог, содержимое которого заполнит образ UFS2 для PS5.",
        ["PS5Filename"] = "Имя выходного файла",
        ["PS5FilenameWatermark"] = "Путь к выходному файлу .img (например, ps5_image.img)",
        ["PS5Preset"] = "Конфигурация",
        ["PS5UseMakefs"] = "Использовать makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Использовать newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Создать образ PS5",
        ["PS5ErrorInputDirectory"] = "Пожалуйста, укажите входной каталог.",
        ["PS5ErrorFilename"] = "Пожалуйста, укажите путь к выходному файлу образа.",
        ["PS5Success"] = "Образ UFS2, совместимый с PS5, успешно создан.",
        ["Browse"] = "Обзор...",

        // Settings
        ["Language"] = "Язык",
        ["LanguageDescription"] = "Выберите язык отображения приложения.",
        ["SettingsTitle"] = "Настройки приложения",
        ["CurrentLanguage"] = "Текущий язык",
    };

    private static Dictionary<string, string> GetHindiStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "UFS1/UFS2 फ़ाइल सिस्टम इमेज बनाएँ, निरीक्षण करें और प्रबंधित करें",
        ["OutputLog"] = "आउटपुट लॉग",
        ["Clear"] = "साफ़ करें",
        ["Detach"] = "अलग करें",

        // Tab Headers
        ["TabCreateFilesystem"] = "फ़ाइल सिस्टम बनाएँ",
        ["TabFilesystemOperations"] = "फ़ाइल सिस्टम संचालन",
        ["TabMaintenance"] = "रखरखाव",
        ["TabDeviceMount"] = "डिवाइस और माउंट",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "सेटिंग्स",

        // Create Filesystem
        ["ImageFile"] = "इमेज फ़ाइल",
        ["ImagePathWatermark"] = "आउटपुट .img फ़ाइल का पथ",
        ["ImagePathHint"] = "या मौजूदा फ़ाइलों से बनाने के लिए नीचे इनपुट डायरेक्टरी से भरें।",
        ["FilesystemOptions"] = "फ़ाइल सिस्टम विकल्प",
        ["FilesystemFormat"] = "फ़ाइल सिस्टम फ़ॉर्मेट",
        ["BlockSize"] = "ब्लॉक आकार",
        ["FragmentSize"] = "फ़्रैगमेंट आकार",
        ["SectorSize"] = "सेक्टर आकार",
        ["VolumeName"] = "वॉल्यूम नाम",
        ["VolumeNameWatermark"] = "वैकल्पिक वॉल्यूम लेबल",
        ["MinFreePercent"] = "न्यूनतम मुक्त %",
        ["Optimization"] = "अनुकूलन",
        ["BytesPerInode"] = "प्रति Inode बाइट्स",
        ["BytesPerInodeWatermark"] = "0 = स्वचालित",
        ["ImageSizeMB"] = "इमेज आकार (MB)",
        ["InputDirectory"] = "इनपुट डायरेक्टरी (makefs)",
        ["InputDirectoryWatermark"] = "उस डायरेक्टरी का पथ जिसकी सामग्री इमेज को भरती है",
        ["InputDirectoryHint"] = "यदि सेट किया गया है, तो इमेज का आकार डायरेक्टरी की सामग्री से स्वचालित रूप से निर्धारित होता है।",
        ["Flags"] = "फ़्लैग",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "सामग्री मिटाएँ",
        ["DryRun"] = "ड्राई रन",
        ["CreateFilesystem"] = "फ़ाइल सिस्टम बनाएँ",

        // Filesystem Operations
        ["ImagePath"] = "इमेज पथ",
        ["ImagePathFSWatermark"] = ".img फ़ाइल का पथ",
        ["FSPath"] = "FS पथ",
        ["Info"] = "जानकारी",
        ["ListLS"] = "सूची (LS)",
        ["Extract"] = "निकालें",
        ["Add"] = "जोड़ें",
        ["Delete"] = "हटाएँ",
        ["Replace"] = "बदलें",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "स्थानीय पथ",
        ["LocalPathWatermark"] = "जोड़ने या बदलने के लिए स्थानीय फ़ाइल/डायरेक्टरी",
        ["OutputDirectory"] = "आउटपुट डायरेक्टरी",
        ["OutputDirectoryWatermark"] = "निकालने का गंतव्य",
        ["ChmodMode"] = "Chmod मोड",
        ["RecursiveChmod"] = "रिकर्सिव Chmod",
        ["DirectoryListing"] = "डायरेक्टरी सूची",
        ["Name"] = "नाम",
        ["Inode"] = "Inode",
        ["Type"] = "प्रकार",
        ["SuperblockInformation"] = "सुपरब्लॉक जानकारी",

        // Maintenance
        ["TuneFilesystem"] = "फ़ाइल सिस्टम ट्यून करें (tunefs)",
        ["NewVolumeName"] = "नया वॉल्यूम नाम",
        ["PrintOnly"] = "केवल प्रिंट करें (कोई बदलाव नहीं)",
        ["EnableSoftUpdates"] = "Soft Updates सक्षम करें",
        ["EnableSUJournaling"] = "SU Journaling सक्षम करें",
        ["TuneButton"] = "फ़ाइल सिस्टम ट्यून करें",
        ["GrowFilesystem"] = "फ़ाइल सिस्टम बढ़ाएँ (growfs)",
        ["NewSizeMB"] = "नया आकार (MB)",
        ["GrowButton"] = "फ़ाइल सिस्टम बढ़ाएँ",
        ["CheckFilesystem"] = "फ़ाइल सिस्टम जाँचें (fsck)",
        ["PreenAutoFix"] = "Preen (स्वतः-सुधार)",
        ["DebugOutput"] = "डीबग आउटपुट",
        ["CheckButton"] = "फ़ाइल सिस्टम जाँचें",

        // Device & Mount
        ["DeviceMountNotice"] = "नोट: डिवाइस और माउंट संचालन केवल Windows पर Dokan ड्राइवर स्थापित होने पर उपलब्ध हैं।",
        ["DeviceInformation"] = "डिवाइस जानकारी",
        ["DevicePath"] = "डिवाइस पथ",
        ["ShowInfo"] = "जानकारी दिखाएँ",
        ["MountFilesystem"] = "फ़ाइल सिस्टम माउंट करें",
        ["DriveLetter"] = "ड्राइव अक्षर",
        ["ReadWriteMode"] = "पढ़ने/लिखने का मोड",
        ["Mount"] = "माउंट",
        ["UnmountFilesystem"] = "फ़ाइल सिस्टम अनमाउंट करें",
        ["Unmount"] = "अनमाउंट",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 त्वरित निर्माण",
        ["PS5Description"] = "PS5 संगतता के लिए एक डायरेक्टरी से UFS2 फ़ाइल सिस्टम इमेज बनाएँ।",
        ["PS5InputDirectory"] = "इनपुट डायरेक्टरी",
        ["PS5InputDirectoryWatermark"] = "इमेज में शामिल करने के लिए फ़ाइलों वाली डायरेक्टरी का पथ",
        ["PS5InputDirectoryHint"] = "उस डायरेक्टरी का चयन करें जिसकी सामग्री PS5 UFS2 इमेज को भरेगी।",
        ["PS5Filename"] = "आउटपुट फ़ाइल नाम",
        ["PS5FilenameWatermark"] = "आउटपुट .img फ़ाइल का पथ (उदा., ps5_image.img)",
        ["PS5Preset"] = "कॉन्फ़िगरेशन",
        ["PS5UseMakefs"] = "makefs उपयोग करें",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "newfs उपयोग करें",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "PS5 इमेज बनाएँ",
        ["PS5ErrorInputDirectory"] = "कृपया एक इनपुट डायरेक्टरी निर्दिष्ट करें।",
        ["PS5ErrorFilename"] = "कृपया एक आउटपुट इमेज फ़ाइल पथ निर्दिष्ट करें।",
        ["PS5Success"] = "PS5-संगत UFS2 इमेज सफलतापूर्वक बनाई गई।",
        ["Browse"] = "ब्राउज़ करें...",

        // Settings
        ["Language"] = "भाषा",
        ["LanguageDescription"] = "एप्लिकेशन के लिए प्रदर्शन भाषा चुनें।",
        ["SettingsTitle"] = "एप्लिकेशन सेटिंग्स",
        ["CurrentLanguage"] = "वर्तमान भाषा",
    };

    private static Dictionary<string, string> GetKoreanStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "UFS1/UFS2 파일 시스템 이미지 생성, 검사 및 관리",
        ["OutputLog"] = "출력 로그",
        ["Clear"] = "지우기",
        ["Detach"] = "분리",

        // Tab Headers
        ["TabCreateFilesystem"] = "파일 시스템 생성",
        ["TabFilesystemOperations"] = "파일 시스템 작업",
        ["TabMaintenance"] = "유지 관리",
        ["TabDeviceMount"] = "장치 및 마운트",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "설정",

        // Create Filesystem
        ["ImageFile"] = "이미지 파일",
        ["ImagePathWatermark"] = "출력 .img 파일 경로",
        ["ImagePathHint"] = "또는 아래 입력 디렉터리를 통해 기존 파일에서 생성할 수 있습니다.",
        ["FilesystemOptions"] = "파일 시스템 옵션",
        ["FilesystemFormat"] = "파일 시스템 형식",
        ["BlockSize"] = "블록 크기",
        ["FragmentSize"] = "프래그먼트 크기",
        ["SectorSize"] = "섹터 크기",
        ["VolumeName"] = "볼륨 이름",
        ["VolumeNameWatermark"] = "선택적 볼륨 레이블",
        ["MinFreePercent"] = "최소 여유 공간 %",
        ["Optimization"] = "최적화",
        ["BytesPerInode"] = "Inode당 바이트",
        ["BytesPerInodeWatermark"] = "0 = 자동",
        ["ImageSizeMB"] = "이미지 크기 (MB)",
        ["InputDirectory"] = "입력 디렉터리 (makefs)",
        ["InputDirectoryWatermark"] = "이미지를 채울 콘텐츠가 있는 디렉터리 경로",
        ["InputDirectoryHint"] = "설정된 경우 디렉터리 내용에서 이미지 크기가 자동으로 결정됩니다.",
        ["Flags"] = "플래그",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "내용 지우기",
        ["DryRun"] = "시험 실행",
        ["CreateFilesystem"] = "파일 시스템 생성",

        // Filesystem Operations
        ["ImagePath"] = "이미지 경로",
        ["ImagePathFSWatermark"] = ".img 파일 경로",
        ["FSPath"] = "FS 경로",
        ["Info"] = "정보",
        ["ListLS"] = "목록 (LS)",
        ["Extract"] = "추출",
        ["Add"] = "추가",
        ["Delete"] = "삭제",
        ["Replace"] = "교체",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "로컬 경로",
        ["LocalPathWatermark"] = "추가 또는 교체할 로컬 파일/디렉터리",
        ["OutputDirectory"] = "출력 디렉터리",
        ["OutputDirectoryWatermark"] = "추출 대상 위치",
        ["ChmodMode"] = "Chmod 모드",
        ["RecursiveChmod"] = "재귀적 Chmod",
        ["DirectoryListing"] = "디렉터리 목록",
        ["Name"] = "이름",
        ["Inode"] = "Inode",
        ["Type"] = "유형",
        ["SuperblockInformation"] = "슈퍼블록 정보",

        // Maintenance
        ["TuneFilesystem"] = "파일 시스템 튜닝 (tunefs)",
        ["NewVolumeName"] = "새 볼륨 이름",
        ["PrintOnly"] = "보기만 (변경 없음)",
        ["EnableSoftUpdates"] = "Soft Updates 활성화",
        ["EnableSUJournaling"] = "SU Journaling 활성화",
        ["TuneButton"] = "파일 시스템 튜닝",
        ["GrowFilesystem"] = "파일 시스템 확장 (growfs)",
        ["NewSizeMB"] = "새 크기 (MB)",
        ["GrowButton"] = "파일 시스템 확장",
        ["CheckFilesystem"] = "파일 시스템 검사 (fsck)",
        ["PreenAutoFix"] = "Preen (자동 수정)",
        ["DebugOutput"] = "디버그 출력",
        ["CheckButton"] = "파일 시스템 검사",

        // Device & Mount
        ["DeviceMountNotice"] = "참고: 장치 및 마운트 작업은 Dokan 드라이버가 설치된 Windows에서만 사용할 수 있습니다.",
        ["DeviceInformation"] = "장치 정보",
        ["DevicePath"] = "장치 경로",
        ["ShowInfo"] = "정보 표시",
        ["MountFilesystem"] = "파일 시스템 마운트",
        ["DriveLetter"] = "드라이브 문자",
        ["ReadWriteMode"] = "읽기/쓰기 모드",
        ["Mount"] = "마운트",
        ["UnmountFilesystem"] = "파일 시스템 마운트 해제",
        ["Unmount"] = "마운트 해제",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 빠른 생성",
        ["PS5Description"] = "PS5 호환을 위해 디렉터리에서 UFS2 파일 시스템 이미지를 생성합니다.",
        ["PS5InputDirectory"] = "입력 디렉터리",
        ["PS5InputDirectoryWatermark"] = "이미지에 포함할 파일이 있는 디렉터리 경로",
        ["PS5InputDirectoryHint"] = "PS5 UFS2 이미지를 채울 콘텐츠가 있는 디렉터리를 선택하세요.",
        ["PS5Filename"] = "출력 파일 이름",
        ["PS5FilenameWatermark"] = "출력 .img 파일 경로 (예: ps5_image.img)",
        ["PS5Preset"] = "구성",
        ["PS5UseMakefs"] = "makefs 사용",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "newfs 사용",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "PS5 이미지 생성",
        ["PS5ErrorInputDirectory"] = "입력 디렉터리를 지정하세요.",
        ["PS5ErrorFilename"] = "출력 이미지 파일 경로를 지정하세요.",
        ["PS5Success"] = "PS5 호환 UFS2 이미지가 성공적으로 생성되었습니다.",
        ["Browse"] = "찾아보기...",

        // Settings
        ["Language"] = "언어",
        ["LanguageDescription"] = "애플리케이션의 표시 언어를 선택하세요.",
        ["SettingsTitle"] = "애플리케이션 설정",
        ["CurrentLanguage"] = "현재 언어",
    };

    private static Dictionary<string, string> GetTurkishStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "UFS1/UFS2 dosya sistemi imajları oluşturun, inceleyin ve yönetin",
        ["OutputLog"] = "Çıktı Günlüğü",
        ["Clear"] = "Temizle",
        ["Detach"] = "Ayır",

        // Tab Headers
        ["TabCreateFilesystem"] = "Dosya Sistemi Oluştur",
        ["TabFilesystemOperations"] = "Dosya Sistemi İşlemleri",
        ["TabMaintenance"] = "Bakım",
        ["TabDeviceMount"] = "Aygıt ve Bağlama",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Ayarlar",

        // Create Filesystem
        ["ImageFile"] = "İmaj Dosyası",
        ["ImagePathWatermark"] = "Çıktı .img dosyasının yolu",
        ["ImagePathHint"] = "Veya mevcut dosyalardan oluşturmak için aşağıdaki Giriş Dizinini kullanın.",
        ["FilesystemOptions"] = "Dosya Sistemi Seçenekleri",
        ["FilesystemFormat"] = "Dosya Sistemi Biçimi",
        ["BlockSize"] = "Blok Boyutu",
        ["FragmentSize"] = "Parça Boyutu",
        ["SectorSize"] = "Sektör Boyutu",
        ["VolumeName"] = "Birim Adı",
        ["VolumeNameWatermark"] = "İsteğe bağlı birim etiketi",
        ["MinFreePercent"] = "Min Boş %",
        ["Optimization"] = "Optimizasyon",
        ["BytesPerInode"] = "Inode Başına Bayt",
        ["BytesPerInodeWatermark"] = "0 = otomatik",
        ["ImageSizeMB"] = "İmaj Boyutu (MB)",
        ["InputDirectory"] = "Giriş Dizini (makefs)",
        ["InputDirectoryWatermark"] = "İçeriği imajı dolduracak dizinin yolu",
        ["InputDirectoryHint"] = "Ayarlanırsa, imaj boyutu dizin içeriğinden otomatik olarak belirlenir.",
        ["Flags"] = "Bayraklar",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "İçeriği Sil",
        ["DryRun"] = "Deneme Çalıştırması",
        ["CreateFilesystem"] = "Dosya Sistemi Oluştur",

        // Filesystem Operations
        ["ImagePath"] = "İmaj Yolu",
        ["ImagePathFSWatermark"] = ".img dosyasının yolu",
        ["FSPath"] = "FS Yolu",
        ["Info"] = "Bilgi",
        ["ListLS"] = "Listele (LS)",
        ["Extract"] = "Çıkart",
        ["Add"] = "Ekle",
        ["Delete"] = "Sil",
        ["Replace"] = "Değiştir",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Yerel Yol",
        ["LocalPathWatermark"] = "Ekleme veya Değiştirme için yerel dosya/dizin",
        ["OutputDirectory"] = "Çıktı Dizini",
        ["OutputDirectoryWatermark"] = "Çıkartma hedefi",
        ["ChmodMode"] = "Chmod Modu",
        ["RecursiveChmod"] = "Özyinelemeli Chmod",
        ["DirectoryListing"] = "Dizin Listesi",
        ["Name"] = "Ad",
        ["Inode"] = "Inode",
        ["Type"] = "Tür",
        ["SuperblockInformation"] = "Süperblok Bilgileri",

        // Maintenance
        ["TuneFilesystem"] = "Dosya Sistemi Ayarla (tunefs)",
        ["NewVolumeName"] = "Yeni birim adı",
        ["PrintOnly"] = "Yalnızca Yazdır (değişiklik yok)",
        ["EnableSoftUpdates"] = "Soft Updates Etkinleştir",
        ["EnableSUJournaling"] = "SU Journaling Etkinleştir",
        ["TuneButton"] = "Dosya Sistemi Ayarla",
        ["GrowFilesystem"] = "Dosya Sistemi Büyüt (growfs)",
        ["NewSizeMB"] = "Yeni Boyut (MB)",
        ["GrowButton"] = "Dosya Sistemi Büyüt",
        ["CheckFilesystem"] = "Dosya Sistemi Kontrol Et (fsck)",
        ["PreenAutoFix"] = "Preen (otomatik düzelt)",
        ["DebugOutput"] = "Hata ayıklama çıktısı",
        ["CheckButton"] = "Dosya Sistemi Kontrol Et",

        // Device & Mount
        ["DeviceMountNotice"] = "Not: Aygıt ve bağlama işlemleri yalnızca Dokan sürücüsü yüklü olan Windows'ta kullanılabilir.",
        ["DeviceInformation"] = "Aygıt Bilgileri",
        ["DevicePath"] = "Aygıt Yolu",
        ["ShowInfo"] = "Bilgi Göster",
        ["MountFilesystem"] = "Dosya Sistemi Bağla",
        ["DriveLetter"] = "Sürücü Harfi",
        ["ReadWriteMode"] = "Okuma/Yazma modu",
        ["Mount"] = "Bağla",
        ["UnmountFilesystem"] = "Dosya Sistemi Ayır",
        ["Unmount"] = "Ayır",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "PS5 Hızlı Oluşturma",
        ["PS5Description"] = "PS5 uyumluluğu için bir dizinden UFS2 dosya sistemi imajı oluşturun.",
        ["PS5InputDirectory"] = "Giriş Dizini",
        ["PS5InputDirectoryWatermark"] = "İmaja dahil edilecek dosyaların bulunduğu dizin yolu",
        ["PS5InputDirectoryHint"] = "İçeriği PS5 UFS2 imajını dolduracak dizini seçin.",
        ["PS5Filename"] = "Çıktı Dosya Adı",
        ["PS5FilenameWatermark"] = "Çıktı .img dosyasının yolu (ör. ps5_image.img)",
        ["PS5Preset"] = "Yapılandırma",
        ["PS5UseMakefs"] = "makefs Kullan",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "newfs Kullan",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "PS5 İmajı Oluştur",
        ["PS5ErrorInputDirectory"] = "Lütfen bir giriş dizini belirtin.",
        ["PS5ErrorFilename"] = "Lütfen bir çıktı imaj dosyası yolu belirtin.",
        ["PS5Success"] = "PS5 uyumlu UFS2 imajı başarıyla oluşturuldu.",
        ["Browse"] = "Gözat...",

        // Settings
        ["Language"] = "Dil",
        ["LanguageDescription"] = "Uygulama için görüntüleme dilini seçin.",
        ["SettingsTitle"] = "Uygulama Ayarları",
        ["CurrentLanguage"] = "Geçerli Dil",
    };

    private static Dictionary<string, string> GetItalianStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Crea, ispeziona e gestisci immagini di file system UFS1/UFS2",
        ["OutputLog"] = "Registro di output",
        ["Clear"] = "Cancella",
        ["Detach"] = "Stacca",

        // Tab Headers
        ["TabCreateFilesystem"] = "Crea file system",
        ["TabFilesystemOperations"] = "Operazioni file system",
        ["TabMaintenance"] = "Manutenzione",
        ["TabDeviceMount"] = "Dispositivo e montaggio",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Impostazioni",

        // Create Filesystem
        ["ImageFile"] = "File immagine",
        ["ImagePathWatermark"] = "Percorso del file .img di output",
        ["ImagePathHint"] = "Oppure compilare tramite la directory di input sottostante per creare da file esistenti.",
        ["FilesystemOptions"] = "Opzioni file system",
        ["FilesystemFormat"] = "Formato file system",
        ["BlockSize"] = "Dimensione blocco",
        ["FragmentSize"] = "Dimensione frammento",
        ["SectorSize"] = "Dimensione settore",
        ["VolumeName"] = "Nome volume",
        ["VolumeNameWatermark"] = "Etichetta volume opzionale",
        ["MinFreePercent"] = "Min libero %",
        ["Optimization"] = "Ottimizzazione",
        ["BytesPerInode"] = "Byte per Inode",
        ["BytesPerInodeWatermark"] = "0 = automatico",
        ["ImageSizeMB"] = "Dimensione immagine (MB)",
        ["InputDirectory"] = "Directory di input (makefs)",
        ["InputDirectoryWatermark"] = "Percorso della directory il cui contenuto popola l'immagine",
        ["InputDirectoryHint"] = "Se impostata, la dimensione dell'immagine viene determinata automaticamente dal contenuto della directory.",
        ["Flags"] = "Flag",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Cancella contenuto",
        ["DryRun"] = "Esecuzione di prova",
        ["CreateFilesystem"] = "Crea file system",

        // Filesystem Operations
        ["ImagePath"] = "Percorso immagine",
        ["ImagePathFSWatermark"] = "Percorso del file .img",
        ["FSPath"] = "Percorso FS",
        ["Info"] = "Informazioni",
        ["ListLS"] = "Elenco (LS)",
        ["Extract"] = "Estrai",
        ["Add"] = "Aggiungi",
        ["Delete"] = "Elimina",
        ["Replace"] = "Sostituisci",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Percorso locale",
        ["LocalPathWatermark"] = "File/directory locale per Aggiungi o Sostituisci",
        ["OutputDirectory"] = "Directory di output",
        ["OutputDirectoryWatermark"] = "Destinazione estrazione",
        ["ChmodMode"] = "Modalità Chmod",
        ["RecursiveChmod"] = "Chmod ricorsivo",
        ["DirectoryListing"] = "Elenco directory",
        ["Name"] = "Nome",
        ["Inode"] = "Inode",
        ["Type"] = "Tipo",
        ["SuperblockInformation"] = "Informazioni superblocco",

        // Maintenance
        ["TuneFilesystem"] = "Regola file system (tunefs)",
        ["NewVolumeName"] = "Nuovo nome volume",
        ["PrintOnly"] = "Solo visualizzazione (nessuna modifica)",
        ["EnableSoftUpdates"] = "Abilita Soft Updates",
        ["EnableSUJournaling"] = "Abilita SU Journaling",
        ["TuneButton"] = "Regola file system",
        ["GrowFilesystem"] = "Espandi file system (growfs)",
        ["NewSizeMB"] = "Nuova dimensione (MB)",
        ["GrowButton"] = "Espandi file system",
        ["CheckFilesystem"] = "Controlla file system (fsck)",
        ["PreenAutoFix"] = "Preen (correzione automatica)",
        ["DebugOutput"] = "Output di debug",
        ["CheckButton"] = "Controlla file system",

        // Device & Mount
        ["DeviceMountNotice"] = "Nota: le operazioni di dispositivo e montaggio sono disponibili solo su Windows con il driver Dokan installato.",
        ["DeviceInformation"] = "Informazioni dispositivo",
        ["DevicePath"] = "Percorso dispositivo",
        ["ShowInfo"] = "Mostra informazioni",
        ["MountFilesystem"] = "Monta file system",
        ["DriveLetter"] = "Lettera unità",
        ["ReadWriteMode"] = "Modalità lettura/scrittura",
        ["Mount"] = "Monta",
        ["UnmountFilesystem"] = "Smonta file system",
        ["Unmount"] = "Smonta",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "Creazione rapida PS5",
        ["PS5Description"] = "Crea un'immagine di file system UFS2 da una directory per la compatibilità PS5.",
        ["PS5InputDirectory"] = "Directory di input",
        ["PS5InputDirectoryWatermark"] = "Percorso della directory con i file da includere nell'immagine",
        ["PS5InputDirectoryHint"] = "Seleziona la directory il cui contenuto popolerà l'immagine UFS2 PS5.",
        ["PS5Filename"] = "Nome file di output",
        ["PS5FilenameWatermark"] = "Percorso del file .img di output (es. ps5_image.img)",
        ["PS5Preset"] = "Configurazione",
        ["PS5UseMakefs"] = "Usa makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Usa newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Crea immagine PS5",
        ["PS5ErrorInputDirectory"] = "Specificare una directory di input.",
        ["PS5ErrorFilename"] = "Specificare un percorso per il file immagine di output.",
        ["PS5Success"] = "Immagine UFS2 compatibile con PS5 creata con successo.",
        ["Browse"] = "Sfoglia...",

        // Settings
        ["Language"] = "Lingua",
        ["LanguageDescription"] = "Seleziona la lingua di visualizzazione dell'applicazione.",
        ["SettingsTitle"] = "Impostazioni applicazione",
        ["CurrentLanguage"] = "Lingua corrente",
    };

    private static Dictionary<string, string> GetPortugueseStrings() => new()
    {
        // Main Window
        ["AppTitle"] = "UFS2 Tool",
        ["AppSubtitle"] = "Criar, inspecionar e gerenciar imagens de sistemas de arquivos UFS1/UFS2",
        ["OutputLog"] = "Registro de saída",
        ["Clear"] = "Limpar",
        ["Detach"] = "Separar",

        // Tab Headers
        ["TabCreateFilesystem"] = "Criar sistema de arquivos",
        ["TabFilesystemOperations"] = "Operações do sistema de arquivos",
        ["TabMaintenance"] = "Manutenção",
        ["TabDeviceMount"] = "Dispositivo e montagem",
        ["TabPS5"] = "PS5",
        ["TabSettings"] = "Configurações",

        // Create Filesystem
        ["ImageFile"] = "Arquivo de imagem",
        ["ImagePathWatermark"] = "Caminho para o arquivo .img de saída",
        ["ImagePathHint"] = "Ou preencha pelo diretório de entrada abaixo para criar a partir de arquivos existentes.",
        ["FilesystemOptions"] = "Opções do sistema de arquivos",
        ["FilesystemFormat"] = "Formato do sistema de arquivos",
        ["BlockSize"] = "Tamanho do bloco",
        ["FragmentSize"] = "Tamanho do fragmento",
        ["SectorSize"] = "Tamanho do setor",
        ["VolumeName"] = "Nome do volume",
        ["VolumeNameWatermark"] = "Rótulo de volume opcional",
        ["MinFreePercent"] = "Mín. livre %",
        ["Optimization"] = "Otimização",
        ["BytesPerInode"] = "Bytes por Inode",
        ["BytesPerInodeWatermark"] = "0 = automático",
        ["ImageSizeMB"] = "Tamanho da imagem (MB)",
        ["InputDirectory"] = "Diretório de entrada (makefs)",
        ["InputDirectoryWatermark"] = "Caminho para o diretório cujo conteúdo preenche a imagem",
        ["InputDirectoryHint"] = "Se definido, o tamanho da imagem é determinado automaticamente a partir do conteúdo do diretório.",
        ["Flags"] = "Opções",
        ["SoftUpdates"] = "Soft Updates",
        ["SUJournaling"] = "SU Journaling",
        ["TRIM"] = "TRIM",
        ["EraseContents"] = "Apagar conteúdo",
        ["DryRun"] = "Execução de teste",
        ["CreateFilesystem"] = "Criar sistema de arquivos",

        // Filesystem Operations
        ["ImagePath"] = "Caminho da imagem",
        ["ImagePathFSWatermark"] = "Caminho para o arquivo .img",
        ["FSPath"] = "Caminho FS",
        ["Info"] = "Informações",
        ["ListLS"] = "Listar (LS)",
        ["Extract"] = "Extrair",
        ["Add"] = "Adicionar",
        ["Delete"] = "Excluir",
        ["Replace"] = "Substituir",
        ["Chmod"] = "Chmod",
        ["LocalPath"] = "Caminho local",
        ["LocalPathWatermark"] = "Arquivo/diretório local para Adicionar ou Substituir",
        ["OutputDirectory"] = "Diretório de saída",
        ["OutputDirectoryWatermark"] = "Destino da extração",
        ["ChmodMode"] = "Modo Chmod",
        ["RecursiveChmod"] = "Chmod recursivo",
        ["DirectoryListing"] = "Listagem de diretório",
        ["Name"] = "Nome",
        ["Inode"] = "Inode",
        ["Type"] = "Tipo",
        ["SuperblockInformation"] = "Informações do superbloco",

        // Maintenance
        ["TuneFilesystem"] = "Ajustar sistema de arquivos (tunefs)",
        ["NewVolumeName"] = "Novo nome do volume",
        ["PrintOnly"] = "Apenas visualizar (sem alterações)",
        ["EnableSoftUpdates"] = "Ativar Soft Updates",
        ["EnableSUJournaling"] = "Ativar SU Journaling",
        ["TuneButton"] = "Ajustar sistema de arquivos",
        ["GrowFilesystem"] = "Expandir sistema de arquivos (growfs)",
        ["NewSizeMB"] = "Novo tamanho (MB)",
        ["GrowButton"] = "Expandir sistema de arquivos",
        ["CheckFilesystem"] = "Verificar sistema de arquivos (fsck)",
        ["PreenAutoFix"] = "Preen (correção automática)",
        ["DebugOutput"] = "Saída de depuração",
        ["CheckButton"] = "Verificar sistema de arquivos",

        // Device & Mount
        ["DeviceMountNotice"] = "Nota: As operações de dispositivo e montagem estão disponíveis apenas no Windows com o driver Dokan instalado.",
        ["DeviceInformation"] = "Informações do dispositivo",
        ["DevicePath"] = "Caminho do dispositivo",
        ["ShowInfo"] = "Mostrar informações",
        ["MountFilesystem"] = "Montar sistema de arquivos",
        ["DriveLetter"] = "Letra da unidade",
        ["ReadWriteMode"] = "Modo leitura/escrita",
        ["Mount"] = "Montar",
        ["UnmountFilesystem"] = "Desmontar sistema de arquivos",
        ["Unmount"] = "Desmontar",

        // PS5 Quick Create
        ["PS5QuickCreate"] = "Criação rápida PS5",
        ["PS5Description"] = "Criar uma imagem de sistema de arquivos UFS2 a partir de um diretório para compatibilidade com PS5.",
        ["PS5InputDirectory"] = "Diretório de entrada",
        ["PS5InputDirectoryWatermark"] = "Caminho para o diretório com arquivos a incluir na imagem",
        ["PS5InputDirectoryHint"] = "Selecione o diretório cujo conteúdo preencherá a imagem UFS2 do PS5.",
        ["PS5Filename"] = "Nome do arquivo de saída",
        ["PS5FilenameWatermark"] = "Caminho para o arquivo .img de saída (ex.: ps5_image.img)",
        ["PS5Preset"] = "Configuração",
        ["PS5UseMakefs"] = "Usar makefs",
        ["PS5MakefsHint"] = "UFS2Tool.exe makefs -S 4096 -t ffs -o version=2,minfree=0,softupdates=0,optimization=space $FILENAME $INPUTDIR",
        ["PS5UseNewfs"] = "Usar newfs",
        ["PS5NewfsHint"] = "newfs -D $INPUTDIR $FILENAME",
        ["PS5CreateButton"] = "Criar imagem PS5",
        ["PS5ErrorInputDirectory"] = "Por favor, especifique um diretório de entrada.",
        ["PS5ErrorFilename"] = "Por favor, especifique um caminho para o arquivo de imagem de saída.",
        ["PS5Success"] = "Imagem UFS2 compatível com PS5 criada com sucesso.",
        ["Browse"] = "Procurar...",

        // Settings
        ["Language"] = "Idioma",
        ["LanguageDescription"] = "Selecione o idioma de exibição do aplicativo.",
        ["SettingsTitle"] = "Configurações do aplicativo",
        ["CurrentLanguage"] = "Idioma atual",
    };
}
